steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/coin-web:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/coin-web:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - coin-web
      - --image=gcr.io/$PROJECT_ID/coin-web:$COMMIT_SHA
      - --region=us-west1
      - --platform=managed
      - --allow-unauthenticated
images:
  - 'gcr.io/$PROJECT_ID/coin-web:$COMMIT_SHA'
