options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'
  
steps:
  # Docker 이미지 빌드 (latest 태그도 추가)
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/coin-web:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/coin-web:latest'
      - '.'
  
  # 모든 태그 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/coin-web']
  
  # Cloud Run에 배포
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'coin-web'
      - '--image'
      - 'gcr.io/$PROJECT_ID/coin-web:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'REACT_APP_WS_URL=wss://api.upbit.com/websocket/v1'

# 이미지 목록 (태그 형식 수정)
images:
  - 'gcr.io/$PROJECT_ID/coin-web:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/coin-web:latest'

timeout: '1200s'
