steps:
  # Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/coin-web:$COMMIT_SHA', '.']
  
  # 이미지를 Container Registry에 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/coin-web:$COMMIT_SHA']
  
  # Cloud Run에 배포
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'coin-web'
      - '--image'
      - 'gcr.io/$PROJECT_ID/coin-web:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast3'  # 서울 리전
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'REACT_APP_WS_URL=wss://api.upbit.com/websocket/v1'

# 이미지 태깅
images:
  - 'gcr.io/$PROJECT_ID/coin-web:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/coin-web:latest'

# 빌드 타임아웃 설정
timeout: '1200s'
